#!/usr/bin/env python3
"""Turn ESP32 serial output into the published jitter comparison.

The firmware's stats task prints one line per 5 s window, tagged IDLE or
LOADED depending on whether the comms load generator is running.  Capture both
conditions and this builds the table in docs/jitter-report.md.

    # 1. baseline
    idf.py -B build-idle build flash
    idf.py monitor | tee reports/jitter-idle.log       # let it run 2+ minutes

    # 2. with the comms load generator hammering core 0
    idf.py -B build-loaded -DENABLE_LOAD_GENERATOR=1 build flash
    idf.py monitor | tee reports/jitter-loaded.log

    # 3. compare
    python3 pi/tools/parse_jitter_log.py \\
        --idle reports/jitter-idle.log \\
        --loaded reports/jitter-loaded.log \\
        --out docs/jitter-report.md
"""

from __future__ import annotations

import argparse
import re
import statistics
import sys
from datetime import datetime, timezone
from pathlib import Path

# Matches the jitter_log() output in esp32/main/jitter.c
JITTER_RE = re.compile(
    r"(?P<tag>IDLE|LOADED)\s*:\s*n=(?P<n>\d+)\s+"
    r"period min/mean/max=(?P<pmin>\d+)/(?P<pmean>\d+)/(?P<pmax>\d+) us\s+"
    r"\|dev\| p50=(?P<p50>\d+) p95=(?P<p95>\d+) p99=(?P<p99>\d+) "
    r"p99\.9=(?P<p999>\d+) us\s+"
    r"exec_max=(?P<exec_max>\d+) us\s+"
    r"overruns=(?P<overruns>\d+) overflow=(?P<overflow>\d+)"
)

# Matches the app-level line, for the comms-load context.
APP_RE = re.compile(
    r"loop=(?P<hz>[\d.]+) Hz.*?can rx=(?P<rx>\d+) tx=(?P<tx>\d+) "
    r"dropped=(?P<dropped>\d+)\s+loadgen=(?P<loadgen>on|off)\((?P<frames>\d+) frames\)"
)


def parse(path: Path) -> dict:
    if not path.is_file():
        raise SystemExit(f"no such log: {path}")
    text = path.read_text(errors="replace")

    samples = [m.groupdict() for m in JITTER_RE.finditer(text)]
    if not samples:
        raise SystemExit(
            f"{path}: no jitter lines found. Expected output from the stats "
            f"task in esp32/main/app_main.c - check the log actually came from "
            f"a running node.")

    # Drop the first window: it includes boot and the first CAN negotiation,
    # which is not steady-state behaviour.
    if len(samples) > 1:
        samples = samples[1:]

    def ints(key):
        return [int(s[key]) for s in samples]

    app = [m.groupdict() for m in APP_RE.finditer(text)]
    can_frames = int(app[-1]["rx"]) + int(app[-1]["tx"]) if app else 0
    loadgen_frames = int(app[-1]["frames"]) if app else 0
    dropped = int(app[-1]["dropped"]) if app else 0

    return {
        "tag": samples[-1]["tag"].strip(),
        "windows": len(samples),
        "total_samples": sum(ints("n")),
        "period_min_us": min(ints("pmin")),
        "period_mean_us": round(statistics.fmean(ints("pmean")), 1),
        "period_max_us": max(ints("pmax")),
        "p50_us": max(ints("p50")),
        "p95_us": max(ints("p95")),
        "p99_us": max(ints("p99")),
        "p999_us": max(ints("p999")),
        "exec_max_us": max(ints("exec_max")),
        "overruns": max(ints("overruns")),
        "overflow": max(ints("overflow")),
        "can_frames": can_frames,
        "loadgen_frames": loadgen_frames,
        "can_dropped": dropped,
    }


def row(label: str, key: str, idle: dict, loaded: dict, unit: str = "us") -> str:
    a, b = idle[key], loaded[key]
    if isinstance(a, (int, float)) and isinstance(b, (int, float)) and a:
        delta = f"{(b - a):+g} {unit}"
    else:
        delta = "-"
    return f"| {label} | {a} {unit} | {b} {unit} | {delta} |"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--idle", required=True, type=Path)
    ap.add_argument("--loaded", required=True, type=Path)
    ap.add_argument("--out", default="docs/jitter-report.md")
    ap.add_argument("--board", default="ESP32-WROOM-32, 240 MHz, ESP-IDF v5.x")
    args = ap.parse_args()

    idle = parse(args.idle)
    loaded = parse(args.loaded)
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    nominal = 1000  # us, CONTROL_PERIOD_US
    lines = [
        "# Control-loop jitter under comms load — measured",
        "",
        "Generated by `pi/tools/parse_jitter_log.py` from ESP32 serial logs.",
        "Do not hand-edit.",
        "",
        f"- Generated: {now}",
        f"- Board: {args.board}",
        f"- Control loop: 1000 Hz ({nominal} us nominal), core 1, priority 23",
        "- Comms: core 0, priorities 12 (rx) / 11 (tx) / 6 (load generator)",
        f"- Idle run: {idle['windows']} windows, {idle['total_samples']:,} control ticks",
        f"- Loaded run: {loaded['windows']} windows, "
        f"{loaded['total_samples']:,} control ticks",
        "",
        "## The claim being tested",
        "",
        "Comms load must not perturb the control loop's period. The load",
        "generator exists only to attack that claim: it floods the TWAI TX",
        "queue and burns CPU on core 0 at the same time, which are the two",
        "ways comms could plausibly steal time from control.",
        "",
        "## Results",
        "",
        "\"Period dev\" is the absolute deviation of the measured period",
        f"from the {nominal} us nominal, sampled inside the control task",
        "itself. Lower is better; 0 would be a perfectly periodic loop.",
        "",
        "| Metric | Idle | Under comms load | Delta |",
        "|---|---:|---:|---:|",
        row("Period min", "period_min_us", idle, loaded),
        row("Period mean", "period_mean_us", idle, loaded),
        row("Period max", "period_max_us", idle, loaded),
        row("Period dev p50", "p50_us", idle, loaded),
        row("Period dev p95", "p95_us", idle, loaded),
        row("Period dev p99", "p99_us", idle, loaded),
        row("Period dev p99.9", "p999_us", idle, loaded),
        row("Loop body exec max", "exec_max_us", idle, loaded),
        f"| Deadline overruns | {idle['overruns']} | {loaded['overruns']} | "
        f"{loaded['overruns'] - idle['overruns']:+d} |",
        f"| CAN frames handled | {idle['can_frames']:,} | "
        f"{loaded['can_frames']:,} | "
        f"{loaded['can_frames'] - idle['can_frames']:+,} |",
        f"| Load-generator frames | {idle['loadgen_frames']:,} | "
        f"{loaded['loadgen_frames']:,} | - |",
        "",
        "## Reading this",
        "",
        f"The load generator pushed {loaded['loadgen_frames']:,} extra frames "
        f"through the bus and kept core 0 busy throughout. The figure that",
        "matters is the change in period-deviation p99 and in the number of",
        "deadline overruns: if the separation works, both stay flat.",
        "",
        "**Why it works.** Three mechanisms, in order of importance:",
        "",
        "1. **Core pinning.** The control task owns core 1; every comms task",
        "   is pinned to core 0. Most of the contention simply cannot happen.",
        "2. **Priority.** Control runs at 23, comms at 12/11/6. Even if they",
        "   shared a core, control preempts.",
        "3. **No shared locks.** The setpoint crosses between them through a",
        "   seqlock (`setpoint_mailbox.h`), not a mutex. A mutex would create",
        "   the priority inversion the split exists to avoid — the 1 kHz task",
        "   blocking on a priority-12 task holding a lock.",
        "",
        "The tick itself is dispatched from the `esp_timer` ISR rather than",
        "through the timer service task, removing one scheduling hop from the",
        "path that has to be deterministic.",
        "",
        "## Caveat",
        "",
        "`exec_max` is the worst *observed* loop-body time, not a WCET bound.",
        "This is an empirical measurement, not a static timing analysis; it",
        "shows the design holds under the load it was tested with, which is",
        "not the same as proving a bound for certification.",
        "",
    ]

    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {out}")

    # A blunt pass/fail so this can gate a CI job on real hardware.
    regressed = (loaded["overruns"] > idle["overruns"]
                 or loaded["p99_us"] > max(idle["p99_us"] * 3, idle["p99_us"] + 20))
    if regressed:
        print("REGRESSION: comms load measurably perturbed the control loop")
        return 1
    print("PASS: control-loop timing held under comms load")
    return 0


if __name__ == "__main__":
    sys.exit(main())
